# Generated by Django 3.1.4 on 2021-01-14 16:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('login', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='category',
            fields=[
                ('cate_id', models.CharField(max_length=128, primary_key=True, serialize=False, unique=True, verbose_name='类型编号')),
                ('cate_name', models.CharField(max_length=256, verbose_name='类型名称')),
            ],
            options={
                'db_table': 'stock_category',
            },
        ),
        migrations.CreateModel(
            name='stock_relate',
            fields=[
                ('code', models.CharField(max_length=128, primary_key=True, serialize=False, unique=True, verbose_name='股票代码')),
                ('category_id', models.OneToOneField(db_column='category_id', on_delete=django.db.models.deletion.CASCADE, to='stock.category')),
            ],
            options={
                'db_table': 'stock_relate',
            },
        ),
        migrations.CreateModel(
            name='company_info',
            fields=[
                ('code', models.OneToOneField(db_column='code', on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='stock.stock_relate')),
                ('form', models.CharField(max_length=256, null=True, verbose_name='组织形式')),
                ('region', models.CharField(max_length=256, null=True, verbose_name='地域')),
                ('name_c', models.CharField(max_length=256, null=True, verbose_name='中文简称')),
                ('location', models.CharField(max_length=256, null=True, verbose_name='办公地址')),
                ('full_name', models.CharField(max_length=256, null=True, verbose_name='公司全称')),
                ('phone_c', models.CharField(max_length=256, null=True, verbose_name='公司电话')),
                ('name_e', models.CharField(max_length=256, null=True, verbose_name='英语名称')),
                ('email_c', models.EmailField(max_length=254, null=True, verbose_name='公司电子邮箱')),
                ('capital', models.CharField(max_length=256, null=True, verbose_name='注册资本')),
                ('chairman', models.CharField(max_length=256, null=True, verbose_name='董事长')),
                ('number', models.CharField(max_length=256, null=True, verbose_name='员工人数')),
                ('secretary', models.CharField(max_length=256, null=True, verbose_name='董事会秘书')),
                ('representative', models.CharField(max_length=256, null=True, verbose_name='法人代表')),
                ('phone_s', models.CharField(max_length=256, null=True, verbose_name='董秘电话')),
                ('general_manager', models.CharField(max_length=256, null=True, verbose_name='总经理')),
                ('fax_s', models.CharField(max_length=256, null=True, verbose_name='董秘传真')),
                ('website', models.CharField(max_length=256, null=True, verbose_name='信息披露网址')),
                ('newspaper', models.CharField(max_length=256, null=True, verbose_name='信息披露报纸名称')),
                ('business_m', models.TextField(null=True, verbose_name='主营业务')),
                ('business_s', models.TextField(null=True, verbose_name='经营范围')),
                ('history', models.TextField(null=True, verbose_name='公司沿革')),
                ('date_set', models.CharField(max_length=256, null=True, verbose_name='成立日期')),
                ('date_launch', models.CharField(max_length=256, null=True, verbose_name='上市日期')),
                ('type', models.CharField(max_length=256, null=True, verbose_name='发行方式')),
                ('value', models.CharField(max_length=256, null=True, verbose_name='面值')),
                ('num_issue', models.CharField(max_length=256, null=True, verbose_name='发行数量')),
                ('price_issue', models.CharField(max_length=128, null=True, verbose_name='发行价格')),
                ('total_price', models.CharField(max_length=256, null=True, verbose_name='募资资金总额')),
                ('total_issue', models.CharField(max_length=256, null=True, verbose_name='发行费用')),
                ('rate_issue', models.CharField(max_length=128, null=True, verbose_name='发行中签率')),
                ('PE_ratio', models.CharField(max_length=128, null=True, verbose_name='发行市盈率')),
                ('earn_per', models.CharField(max_length=256, null=True, verbose_name='发行后每股收益')),
                ('net_worth', models.CharField(max_length=256, null=True, verbose_name='发行后每股净资产')),
                ('open_first', models.CharField(max_length=256, null=True, verbose_name='上市首日开盘价')),
                ('close_first', models.CharField(max_length=256, null=True, verbose_name='上市首日收盘价')),
                ('turnover_first', models.CharField(max_length=256, null=True, verbose_name='上市首日换手率')),
                ('underwriter', models.CharField(max_length=256, null=True, verbose_name='主承销商')),
                ('sponsor_list', models.CharField(max_length=256, null=True, verbose_name='上市保荐人')),
                ('firm_account', models.CharField(max_length=256, null=True, verbose_name='会计师事务所')),
            ],
            options={
                'db_table': 'stock_company_info',
            },
        ),
        migrations.CreateModel(
            name='CUR_STOCK',
            fields=[
                ('CODE', models.OneToOneField(db_column='code', on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='stock.stock_relate')),
                ('NAME', models.CharField(max_length=256, verbose_name='名称')),
                ('PRICE', models.FloatField(max_length=256, verbose_name='价格')),
                ('PERCENT', models.FloatField(max_length=256, verbose_name='涨跌幅')),
                ('UPDOWN', models.FloatField(max_length=256, verbose_name='涨跌额')),
                ('FIVE_MINUTE', models.FloatField(max_length=256, verbose_name='5分钟涨跌额')),
                ('OPEN', models.FloatField(max_length=256, verbose_name='今开')),
                ('YESTCLOSE', models.FloatField(max_length=256, verbose_name='昨收')),
                ('HIGH', models.FloatField(max_length=256, verbose_name='最高')),
                ('LOW', models.FloatField(max_length=256, verbose_name='最低')),
                ('VOLUME', models.BigIntegerField(verbose_name='成交量')),
                ('TURNOVER', models.FloatField(max_length=256, verbose_name='成交额')),
                ('HS', models.FloatField(max_length=256, verbose_name='换手率')),
                ('LB', models.FloatField(max_length=256, verbose_name='量比')),
                ('WB', models.FloatField(max_length=256, verbose_name='委比')),
                ('ZF', models.FloatField(max_length=256, verbose_name='振幅')),
                ('PE', models.FloatField(max_length=256, verbose_name='市盈率')),
                ('MCAP', models.FloatField(max_length=256, verbose_name='流通市值')),
                ('TCAP', models.FloatField(max_length=256, verbose_name='总市值')),
                ('MFSUM', models.FloatField(max_length=256, verbose_name='每股收益')),
                ('MFRATIO_1', models.FloatField(max_length=256, null=True, verbose_name='净利润')),
                ('MFRATIO_2', models.FloatField(max_length=256, null=True, verbose_name='主营收')),
                ('DATE', models.CharField(max_length=256, verbose_name='爬取时间')),
            ],
            options={
                'db_table': 'CUR_STOCK',
            },
        ),
        migrations.CreateModel(
            name='myFavourite',
            fields=[
                ('c_time', models.TimeField(auto_now_add=True, primary_key=True, serialize=False, unique=True)),
                ('code', models.ForeignKey(db_column='favour_code', on_delete=django.db.models.deletion.CASCADE, related_name='favour_user_code', to='stock.stock_relate')),
                ('id', models.ForeignKey(db_column='user_id', on_delete=django.db.models.deletion.CASCADE, related_name='favourite_user_id', to='login.user')),
            ],
            options={
                'db_table': 'stock_myFavourite',
            },
        ),
        migrations.CreateModel(
            name='history_data',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='日期')),
                ('close', models.FloatField(max_length=256, verbose_name='收盘价')),
                ('high', models.FloatField(max_length=256, verbose_name='最高价')),
                ('low', models.FloatField(max_length=256, verbose_name='最低价')),
                ('open', models.FloatField(max_length=256, verbose_name='开盘价')),
                ('yest_close', models.FloatField(max_length=256, verbose_name='开盘价')),
                ('updown', models.FloatField(max_length=256, verbose_name='涨跌额')),
                ('percent', models.FloatField(max_length=256, verbose_name='涨跌幅')),
                ('hs', models.FloatField(max_length=128, verbose_name='换手率(%)')),
                ('volumn', models.FloatField(max_length=256, verbose_name='成交量(手)')),
                ('turnover', models.FloatField(max_length=256, verbose_name='成交金额(万元)')),
                ('tcap', models.FloatField(max_length=256, verbose_name='总市值')),
                ('mcap', models.FloatField(max_length=256, verbose_name='流通市值')),
                ('code', models.ForeignKey(db_column='code', on_delete=django.db.models.deletion.CASCADE, to='stock.stock_relate')),
            ],
            options={
                'db_table': 'stock_history_data',
            },
        ),
    ]
