# Generated by Django 3.1.4 on 2021-01-14 16:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0002_auto_20210115_0052'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cur_stock',
            name='CODE',
            field=models.OneToOneField(db_column='CODE', on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='stock.stock_relate'),
        ),
    ]
