# Generated by Django 3.1.4 on 2021-01-21 08:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0003_auto_20210115_0057'),
    ]

    operations = [
        migrations.AlterField(
            model_name='history_data',
            name='close',
            field=models.FloatField(max_length=256, null=True, verbose_name='收盘价'),
        ),
        migrations.AlterField(
            model_name='history_data',
            name='high',
            field=models.FloatField(max_length=256, null=True, verbose_name='最高价'),
        ),
        migrations.AlterField(
            model_name='history_data',
            name='hs',
            field=models.FloatField(max_length=128, null=True, verbose_name='换手率(%)'),
        ),
        migrations.AlterField(
            model_name='history_data',
            name='low',
            field=models.FloatField(max_length=256, null=True, verbose_name='最低价'),
        ),
        migrations.AlterField(
            model_name='history_data',
            name='mcap',
            field=models.FloatField(max_length=256, null=True, verbose_name='流通市值'),
        ),
        migrations.AlterField(
            model_name='history_data',
            name='open',
            field=models.FloatField(max_length=256, null=True, verbose_name='开盘价'),
        ),
        migrations.AlterField(
            model_name='history_data',
            name='percent',
            field=models.FloatField(max_length=256, null=True, verbose_name='涨跌幅'),
        ),
        migrations.AlterField(
            model_name='history_data',
            name='tcap',
            field=models.FloatField(max_length=256, null=True, verbose_name='总市值'),
        ),
        migrations.AlterField(
            model_name='history_data',
            name='turnover',
            field=models.FloatField(max_length=256, null=True, verbose_name='成交金额(万元)'),
        ),
        migrations.AlterField(
            model_name='history_data',
            name='updown',
            field=models.FloatField(max_length=256, null=True, verbose_name='涨跌额'),
        ),
        migrations.AlterField(
            model_name='history_data',
            name='volumn',
            field=models.FloatField(max_length=256, null=True, verbose_name='成交量(手)'),
        ),
    ]
