# Generated by Django 3.1.4 on 2021-01-21 08:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0004_auto_20210121_1646'),
    ]

    operations = [
        migrations.AlterField(
            model_name='history_data',
            name='yest_close',
            field=models.FloatField(max_length=256, null=True, verbose_name='开盘价'),
        ),
    ]
