# Generated by Django 3.1.4 on 2021-01-21 08:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0005_auto_20210121_1649'),
    ]

    operations = [
        migrations.AlterField(
            model_name='history_data',
            name='percent',
            field=models.CharField(max_length=256, null=True, verbose_name='涨跌幅'),
        ),
        migrations.AlterField(
            model_name='history_data',
            name='updown',
            field=models.CharField(max_length=256, null=True, verbose_name='涨跌额'),
        ),
    ]
