# Generated by Django 3.1.4 on 2021-01-21 09:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0006_auto_20210121_1658'),
    ]

    operations = [
        migrations.AlterField(
            model_name='history_data',
            name='hs',
            field=models.CharField(max_length=128, null=True, verbose_name='换手率(%)'),
        ),
    ]
