# Generated by Django 3.1.4 on 2021-01-21 09:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0007_auto_20210121_1706'),
    ]

    operations = [
        migrations.AlterField(
            model_name='history_data',
            name='hs',
            field=models.FloatField(max_length=128, null=True, verbose_name='换手率(%)'),
        ),
        migrations.AlterField(
            model_name='history_data',
            name='percent',
            field=models.FloatField(max_length=256, null=True, verbose_name='涨跌幅'),
        ),
        migrations.AlterField(
            model_name='history_data',
            name='updown',
            field=models.FloatField(max_length=256, null=True, verbose_name='涨跌额'),
        ),
    ]
